spring.application.name=personal-task
spring.datasource.url=jdbc:postgresql://localhost:5432/taskDB

spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver


# jpa hibernate configuration

# scheme behavior
spring.jpa.hibernate.ddl-auto=update

# querys in console
spring.jpa.show-sql=true

# legibility in console
spring.jpa.properties.hibernate.format_sql=true

# dev tools
spring.devtools.restart.enabled=true

# all endpoints
management.endpoints.web.exposure.include=health,info,metrics,loggers,env

# all actuator details
management.endpoint.health.show-details=always




